# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class Api:
        type: str
        url: str
    class App:
        name: str
        stage: str
    class MongoDbUri:
        type: str
        value: str
    class OpenAiApiKey:
        type: str
        value: str

